---
  - name: Install MySQL packages
    apt: pkg={{item}} state=installed
    with_items:
      - bundler
      - mysql-server-core-5.5
      - mysql-client-core-5.5
      - libmysqlclient-dev
      - python-mysqldb
      - mysql-server
      - mysql-client
      - build-essential

  - name: Remove the MySQL test database
    action: mysql_db db=test state=absent

  - name: Create global my.cnf
    copy: src=etc.my.cnf dest=/etc/mysql/my.cnf

  - name: Create databases
    mysql_db: name={{item}} state=present collation=utf8_general_ci encoding=utf8
    with_items:
      - "{{db_prefix}}_production"
      - "{{db_prefix}}_staging"
      - "{{db_prefix}}_development"
      - "{{db_prefix}}_test"

  - name: Add deploy DB user and allow access to news_* databases
    mysql_user: name={{user}} password={{password}} host="%" priv=news_production.*:ALL/news_development.*:ALL/news_staging.*:ALL/news_test.*:ALL,GRANT state=present

  - name: Set root password
    mysql_user: name=root password={{password}} host="{{item}}" priv=*.*:ALL,GRANT state=present
    with_items:
      - "{{ansible_hostname}}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Create local my.cnf for root user
    template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

  - name: Restart the MySQL service
    action: service name=mysql state=restarted enabled=true
