---
  - name: Install needed packages for the app
    apt: pkg={{item}} state=installed
    with_items:
      - bundler
      - mysql-client-core-5.5
      - libmysqlclient-dev
      - python-mysqldb
      - mysql-client
      - build-essential
      - nginx
      - firefox
      - xvfb

  - name: Remove nginx default conf
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Copy nginx conf file to available
    template: src=nginx.conf dest=/etc/nginx/sites-available/{{appname}}.conf owner={{user}}

  - name: Symlink it to enabled
    file: src=/etc/nginx/sites-available/{{appname}}.conf dest=/etc/nginx/sites-enabled/00-{{appname}}.conf state=link

  - name: Set up cron for logrotate
    cron: name="{{appname}} Logrotate" job="logrotate -v /etc/logrotate.d/{{appname}}" state=present special_time=daily user={{user}}
